### ISSUE TITLE
Is this classic yespower? 

### ISSUE THREAD

**Issue by ghost** [mgpc-lab/MagpieCoin#1]
Hello! Im trying to setup pool for this coin and i used various repos of yespower for Yiimp and im still getting all blocks rejected with this error from wallet : 2021-03-12 19:19:15 ERROR: CheckProofOfWork() : hash doesn't match nBits
2021-03-12 19:19:15 ERROR: CheckBlock() : proof of work failed
2021-03-12 19:19:15 ERROR: ProcessBlock() : CheckBlock FAILED

My pool is working for yespowerSUGAR, for pyrk yespower so im just curious what is different with this type of algo. Thanks!

**Comment by mgpc-lab** [comment]
static yespower_params_t params = {
        .version = YESPOWER_1_0,
        .N = 2048,
        .r = 32,
        .pers = "Magpies are birds of the Corvidae family.",
        .perslen = 41
    };

**Comment by mgpc-lab** [comment]
yespower 1.0.1, https://github.com/mgpc-lab/cpuminer-opt

Viktor Majko ***@***.***> 于2021年3月13日周六 上午3:33写道：
